Toolkit upgrade
bitzesty/qavs-v2 pull request #51
Opened 2021-07-22 13:30 UTC by mauricioac

2021-07-23 10:39 UTC, dreamfall requested changes

2021-07-23 10:39 UTC, dreamfall commented on app/views/form_award_eligibilities/questions/_number_of_innovative_products.html.slim
> +  = f.input :number_of_innovative_products, input_html: { class: 'tiny innovative_amount_input', autocomplete: "off" }, label_html: { class: 'govuk-body govuk-!-font-weight-bold govuk-!-font-size-36
Can delete this file as well

2021-07-23 10:39 UTC, dreamfall commented on app/views/form_award_eligibilities/questions/_qae_for_trade_award_year.html.slim
> +  = f.input :qae_for_trade_award_year, as: :select, include_blank: true, label: false, input_html: { class: 'trade-awarded-input', autocomplete: "off" }
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/form_award_eligibilities/questions/_sales_above_100_000_pounds.html.slim
>    - collection.reject! { |opts| opts.last == 'skip' } if controller_name == 'form_award_eligibilities'
Can delete this file as well

2021-07-23 10:39 UTC, dreamfall commented on app/views/form_award_eligibilities/questions/_sustainable_development.html.slim
> +  - collection = @eligibility.class.sustainable_development.options
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/form_award_eligibilities/questions/hints/_promoting_social_mobility.html
> +<div>
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/form_award_eligibilities/questions/hints/_social_mobility_activities.html
> -  <strong>Skills development</strong> – providing activities or training to help people from disadvantaged backgrounds to develop hard skills (for example, numeracy, computer literacy, cooking) or so
Can delete this file as well

2021-07-23 10:39 UTC, dreamfall commented on app/views/form_award_eligibilities/show.html.slim
> +                  - if @eligibility.is_a?(Eligibility::Basic) || !input_steps.include?(step.to_s)
This condition is no longer needed

2021-07-23 10:39 UTC, dreamfall commented on app/views/form_award_eligibilities/show.html.slim
>                    - else
Actually this condition is no longer needed as well. That means you can remove `form_award_eligibilities/questions/` folder @mauricioac

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_by_trade_goods_and_services_label_question.html.slim
> +  input name="#{question.input_name}[array]" value="true" type="hidden" *possible_read_only_ops
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_award_holder_question.html.slim
> -= link_to "+ Add Award/Personal honour", new_form_form_answer_awards_url(@form_answer.id, question.award_years_present ? {holder: true} : {}), class: "button button-add if-js-hide",  "data-entity" =>
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_by_years_label_question.html.slim
> +          label.govuk-label
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_by_years_question.html.slim
> -        label
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_form_footer.html.slim
> +            = link_to "Save and come back later", dashboard_url, class: " govuk-button govuk-button--secondary js-save-and-come-back"
Need to bring back `dashboard_link` var.

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_form_footer.html.slim
> +      - if step.next
revert this change as well

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_one_option_by_years_question.html.slim
> +      label.govuk-label
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_pdf_link.html.slim
> +      ' Download your nomination
Should always be `nomination` for QAVS. Condition is no longer needed.

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_step_error.html.slim
> +            ' application
Should always be nominstion.

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_steps_progress_bar.html.slim
> +          - for step in @form.steps do
Need to use `current_steps(@form_answer, current_form_user)` method

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/_trade_commercial_success_question.html.slim
> +
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/confirm.html.slim
> +        ' Your Unique Reference Number (URN) is #{@form_answer.urn}
This needs to be removed as we no longer have URN

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/confirm.html.slim
> +
✂️

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/show.html.slim
> +      = render "qae_form/step_error"
✂️

2021-07-23 10:39 UTC, dreamfall commented on app/views/qae_form/show.html.slim
> +      = render partial: 'qae_form/step', collection: @form.steps, locals: {form: @form, answers: (HashWithIndifferentAccess.new(@form_answer.document || {})), attachments: HashWithIndifferentAccess.n
Should be `.current_steps(@form_answer, current_form_user)`

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/audit_certificate_mailer/notify.text.erb
> +
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/audit_certificate_request_mailer/notify.text.erb
> +
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/audit_certificate_request_mailer/preview/notify.html.slim
> +
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/audit_certificates/_file.html.slim
> +  - att_record = award.audit_certificate
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/audit_certificates/_form.html.slim
> +                  as: :audit_certificate,
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/audit_certificates/_non_js_form.html.slim
> +                  as: :audit_certificate,
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/audit_certificates/_upload_block.html.slim
> +    li.li-audit-upload
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/audit_certificates/show.html.slim
> +
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/collaboration_mailer/access_granted.text.erb
> +<%= @user_who_added.full_name %> has invited you to collaborate with them on a Queen's Award for Enterprise application.
Can delete this file

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/registrations/new.html.slim
> +          ' If you are a marketing company applying on behalf of a client, your client should create an account first, then add you as a collaborator.
I don't think this copy is correct

2021-07-23 10:39 UTC, dreamfall commented on app/views/users/supporter_mailer/success.text.erb
> +You've been chosen by <%= @nominator_name %> to write a letter of support in aid of the nomination of <%= @nominee_name %> for a Queen's Award for Enterprise Promotion.
Can delete this file

2021-07-27 09:49 UTC, dreamfall requested changes

2021-07-27 09:49 UTC, dreamfall commented on app/views/content_only/_award_nickname.html.slim
> +    = render "content_only/award_nickname_block"
@mauricioac I think you've missed it

```
  - if award_type == "innovation"
    = render "content_only/award_nickname_block"
```

This is no longer needed.

2021-07-27 09:49 UTC, dreamfall commented on app/views/qae_form/_form_footer.html.slim
> +            = link_to "Save and come back later", dashboard_url, class: " govuk-button govuk-button--secondary js-save-and-come-back"
https://github.com/bitzesty/qavs-v2/pull/51/files#diff-d8ae559f0c087f6feb9cdd0a046fa2eae0f57a86e5d44283f845602ea44b5314L26

@mauricioac here's the link to var (it was removed as well)

2021-07-27 09:49 UTC, dreamfall commented on config/database.yml
> +  password: postgres
Need to probably check out this file 👮

2021-07-28 11:21 UTC, matthewford commented on config/database.yml
> +  password: postgres
I'm going to be changing these soon anyway in my pr to use env vars.

2021-07-28 12:33 UTC, merged