adds nomination dashboard filters
bitzesty/qavs-v2 pull request #69
Opened 2021-08-05 09:40 UTC by TheDancingClown

https://drive.google.com/file/d/1soVr-PhHbDhAZdTBbjjOLqYNwhgfUYZM/view

- Removes uppercase styling for filter labels
- Removes flag and urn column
- Splits ceremonial county column into assigned lieutenancy and ceremonial county from form
- Adds filters for new columns
- Fixes activity filter to display incomplete forms
- Adds copy help when no forms are checked

![Screenshot 2021-08-05 at 10 36 41](https://user-images.githubusercontent.com/65811538/128328572-e03a6a68-0270-4b92-8a66-177e7056c266.png)
![Screenshot 2021-08-05 at 10 36 53](https://user-images.githubusercontent.com/65811538/128328584-e9dc46aa-4153-421a-b631-dda568092f44.png)
![Screenshot 2021-08-05 at 10 37 05](https://user-images.githubusercontent.com/65811538/128328594-87e2f5e7-cf95-4cf6-9eea-6646794e5dbb.png)

2021-08-05 14:15 UTC, mauricioac requested changes

2021-08-05 14:15 UTC, mauricioac commented on app/javascript/packs/application.js
> +      $(".bulk-assignment-help").addClass("hide")
use `govuk-!-display-none` instead of the `hide` class

2021-08-05 14:15 UTC, mauricioac commented on app/javascript/packs/application.js
> +      $(".bulk-assignment-help").removeClass("hide")
same here

2021-08-05 14:15 UTC, mauricioac commented on app/javascript/packs/application.js
> +      // placeholder: 'Select all',
remove commented code

2021-08-05 14:15 UTC, mauricioac commented on app/views/admin/form_answers/_bulk_assignment_modal.html.slim
> +          h3.govuk-heading-l.mm-modal__title id="modal-bulk-assign-lieutenants-title"
h3 should be `govuk-heading-m`

2021-08-05 14:15 UTC, mauricioac commented on app/views/admin/form_answers/_bulk_assignment_modal.html.slim
> +                        class: "govuk-select govuk-grid-column-one-half"
Selects should be using grid layout. USe that on a wrapper div please

2021-08-05 14:15 UTC, mauricioac commented on app/views/admin/form_answers/index.html.slim
> +        = f.label 'Search', class: 'govuk-visually-hidden'
Make it visible please

2021-08-05 14:53 UTC, TheDancingClown commented on app/views/admin/form_answers/_bulk_assignment_modal.html.slim
> +                        class: "govuk-select govuk-grid-column-one-half"
Removed class to rely on autosizing

2021-08-06 08:20 UTC, mauricioac approved these changes

2021-08-06 08:21 UTC, merged